# Generated by Django 5.1.7 on 2025-03-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PieceDeRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('categorie', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('prxUnitaire', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.IntegerField()),
                ('emplacement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.piecederechange')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'unique_together': {('stock', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='pieces',
            field=models.ManyToManyField(through='stock.StockPiece', to='stock.piecederechange'),
        ),
    ]
