# Generated by Django 5.1.7 on 2025-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecederechange',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_piece/'),
        ),
    ]
