# Generated by Django 5.1.7 on 2025-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_piecederechange_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='emplacement',
        ),
        migrations.AddField(
            model_name='stock',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='nom',
            field=models.CharField(default='stock{id}', max_length=255),
        ),
    ]
