# Generated by Django 5.1.7 on 2025-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_emplacement_stock_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piecederechange',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='longitude',
        ),
        migrations.AddField(
            model_name='stock',
            name='content',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
