# Generated by Django 5.1.7 on 2025-04-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='stock + " " + {stock.id}', max_length=255),
        ),
    ]
