# Generated by Django 5.1.7 on 2025-04-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_piecederechange_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecederechange',
            name='image',
            field=models.ImageField(default='', upload_to='image_piece/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
