# Generated by Django 5.1.7 on 2025-04-28 07:26

import django.db.models.deletion
import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_piecederechange_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecederechange',
            name='image',
        ),
        migrations.CreateModel(
            name='PieceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=stock.models.get_new_upload_path)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stock.piecederechange')),
            ],
        ),
    ]
