# Generated by Django 5.1.7 on 2025-04-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_piecederechange_image_pieceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecederechange',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=50),
        ),
    ]
