# Generated by Django 5.1.7 on 2025-03-19 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('users', '0002_administrateur_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Fonctionnel', 'Fonctionnel'), ('En panne', 'En panne'), ('Maintenance', 'Maintenance')], default='Fonctionnel', max_length=50)),
                ('dateDerniereMaintenance', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='tache',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_taches', to='users.technicien'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='users.technicien'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='machines.tache'),
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('dateDebut', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='machines.machine')),
            ],
        ),
        migrations.DeleteModel(
            name='Technicien',
        ),
    ]
