# Generated by Django 5.1.7 on 2025-03-19 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('statu', models.CharField(choices=[('ouvert', 'ouvert'), ('en cours', 'en cours'), ('résolu', 'résolu')], default='ouvert', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('contenu', models.TextField()),
            ],
        ),
    ]
