# Generated by Django 5.1.7 on 2025-03-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgprob/'),
        ),
    ]
