# Generated by Django 5.1.7 on 2025-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
