# Generated by Django 5.1.7 on 2025-03-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_administrateur_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='numTel',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
