# Generated by Django 5.1.7 on 2025-03-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_utilisateur_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUT', models.CharField(max_length=255)),
                ('prenomUT', models.CharField(max_length=255)),
                ('numIdentifUT', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='nomUT',
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='numIdentifUT',
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='prenomUT',
        ),
    ]
