# Generated by Django 5.1.7 on 2025-03-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_remove_administrateur_nomut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='nomUT',
            new_name='nomuc',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='numIdentifUT',
            new_name='numIdentifuc',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='prenomUT',
            new_name='prenomuc',
        ),
    ]
