# Generated by Django 5.1.7 on 2025-03-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_utilisateursgeres_administrateur_utilisateursgeres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='numidentif',
            new_name='numIdentif',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='numtel',
            new_name='numTel',
        ),
    ]
