# Generated by Django 5.1.7 on 2025-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_rename_numidentif_utilisateur_numidentif_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={'verbose_name': 'Administrateur'},
        ),
        migrations.AlterModelOptions(
            name='magasinier',
            options={'verbose_name': 'Magasinier'},
        ),
        migrations.AlterModelOptions(
            name='operateur',
            options={'verbose_name': 'Operateur'},
        ),
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name': 'Responsable'},
        ),
        migrations.AlterModelOptions(
            name='technicien',
            options={'verbose_name': 'Technicien'},
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='numIdentif',
            new_name='numidentif',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='numTel',
            new_name='numtel',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
