# Generated by Django 5.1.7 on 2025-04-19 08:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_administrateur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_upload_path),
        ),
    ]
