# Generated by Django 5.1.7 on 2025-04-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_utilisateur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgUser/%Y/%m/%d'),
        ),
    ]
